export const WHATSAPP_NUMBER = "573001234567";

export const products = [
    {
        id: "lg-turbodrum",
        name: "LG TurboDrum",
        marca: "LG",
        segmento: "Línea Premium",
        capacidad: "22 lb",
        tipo: "Carga superior",
        precio: "Desde $950.000",
        precioNum: 950000,
        image: "/images/lavadoras/lavadora-lg-carga-superior-19-kilos-wt19ovtb-negro.avif",
        msg: "Hola, estoy interesado en la categoría LG TurboDrum - Línea Premium. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "samsung-digital-18",
        name: "Samsung Digital 18 lb",
        marca: "Samsung",
        segmento: "Línea Premium",
        capacidad: "18 lb",
        tipo: "Digital",
        precio: "Desde $870.000",
        precioNum: 870000,
        image: "/images/lavadoras/lavadora-samsung-bespoke-carga-superior-ai-wash-13-kilos-wa80f13s5bco-negra.avif",
        msg: "Hola, estoy interesado en la categoría Samsung Digital 18 lb - Línea Premium. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "haceb-carga-superior",
        name: "Haceb Carga Superior",
        marca: "Haceb",
        segmento: "Línea Estándar",
        capacidad: "16 lb",
        tipo: "Carga superior",
        precio: "Desde $650.000",
        precioNum: 650000,
        image: "/images/lavadoras/lavadora-gris.avif",
        msg: "Hola, estoy interesado en la categoría Haceb Carga Superior - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "whirlpool-automatica",
        name: "Whirlpool Automática",
        marca: "Whirlpool",
        segmento: "Línea Estándar",
        capacidad: "18 lb",
        tipo: "Automática",
        precio: "Desde $720.000",
        precioNum: 720000,
        image: "/images/lavadoras/lavadora-gris2.avif",
        msg: "Hola, estoy interesado en la categoría Whirlpool Automática - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "mabe-20lb",
        name: "Mabe 20 libras",
        marca: "Mabe",
        segmento: "Línea Estándar",
        capacidad: "20 lb",
        tipo: "Automática",
        precio: "Desde $780.000",
        precioNum: 780000,
        image: "/images/lavadoras/lavadora-mabe-carga-superior-20-kilos-lma0220wdgab0-gris.avif",
        msg: "Hola, estoy interesado en la categoría Mabe 20 libras - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "lg-automatica-20",
        name: "LG Automática 20 lb",
        marca: "LG",
        segmento: "Línea Estándar",
        capacidad: "20 lb",
        tipo: "Automática",
        precio: "Desde $800.000",
        precioNum: 800000,
        image: "/images/lavadoras/lavadora-lg-carga-superior-19-kilos-wt19ovtb-negro2.avif",
        msg: "Hola, estoy interesado en la categoría LG Automática 20 lb - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "samsung-frontal-premium",
        name: "Samsung Frontal Premium",
        marca: "Samsung",
        segmento: "Línea Premium",
        capacidad: "22 lb",
        tipo: "Digital",
        precio: "Desde $980.000",
        precioNum: 980000,
        image: "/images/lavadoras/lavadora-samsung-bespoke-carga-superior-ai-wash-13-kilos-wa80f13s5bco-negra.avif",
        msg: "Hola, estoy interesado en la categoría Samsung Frontal Premium - Línea Premium. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "haceb-automatica-18",
        name: "Haceb Automática 18 lb",
        marca: "Haceb",
        segmento: "Línea Estándar",
        capacidad: "18 lb",
        tipo: "Automática",
        precio: "Desde $680.000",
        precioNum: 680000,
        image: "/images/lavadoras/lavadora-mabe-carga-superior-20-kilos-lma0220wdgab0-gris-interior.avif",
        msg: "Hola, estoy interesado en la categoría Haceb Automática 18 lb - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
];
