export const WHATSAPP_NUMBER = "573001234567";

export const products = [
    {
        id: "lg-turbodrum",
        name: "LG TurboDrum",
        marca: "LG",
        segmento: "Línea Premium",
        capacidad: "22 lb",
        tipo: "Carga superior",
        precio: "Desde $950.000",
        precioNum: 950000,
        image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría LG TurboDrum - Línea Premium. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "samsung-digital-18",
        name: "Samsung Digital 18 lb",
        marca: "Samsung",
        segmento: "Línea Premium",
        capacidad: "18 lb",
        tipo: "Digital",
        precio: "Desde $870.000",
        precioNum: 870000,
        image: "https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría Samsung Digital 18 lb - Línea Premium. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "haceb-carga-superior",
        name: "Haceb Carga Superior",
        marca: "Haceb",
        segmento: "Línea Estándar",
        capacidad: "16 lb",
        tipo: "Carga superior",
        precio: "Desde $650.000",
        precioNum: 650000,
        image: "https://images.unsplash.com/photo-1469460340997-2f854421e72f?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría Haceb Carga Superior - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "whirlpool-automatica",
        name: "Whirlpool Automática",
        marca: "Whirlpool",
        segmento: "Línea Estándar",
        capacidad: "18 lb",
        tipo: "Automática",
        precio: "Desde $720.000",
        precioNum: 720000,
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría Whirlpool Automática - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "mabe-20lb",
        name: "Mabe 20 libras",
        marca: "Mabe",
        segmento: "Línea Estándar",
        capacidad: "20 lb",
        tipo: "Automática",
        precio: "Desde $780.000",
        precioNum: 780000,
        image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría Mabe 20 libras - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "lg-automatica-20",
        name: "LG Automática 20 lb",
        marca: "LG",
        segmento: "Línea Estándar",
        capacidad: "20 lb",
        tipo: "Automática",
        precio: "Desde $800.000",
        precioNum: 800000,
        image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría LG Automática 20 lb - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "samsung-frontal-premium",
        name: "Samsung Frontal Premium",
        marca: "Samsung",
        segmento: "Línea Premium",
        capacidad: "22 lb",
        tipo: "Digital",
        precio: "Desde $980.000",
        precioNum: 980000,
        image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría Samsung Frontal Premium - Línea Premium. ¿Qué opciones tienen disponibles?",
    },
    {
        id: "haceb-automatica-18",
        name: "Haceb Automática 18 lb",
        marca: "Haceb",
        segmento: "Línea Estándar",
        capacidad: "18 lb",
        tipo: "Automática",
        precio: "Desde $680.000",
        precioNum: 680000,
        image: "https://images.unsplash.com/photo-1567473885138-01834a43c975?w=700&q=80",
        msg: "Hola, estoy interesado en la categoría Haceb Automática 18 lb - Línea Estándar. ¿Qué opciones tienen disponibles?",
    },
];